# Identifiant unique de ton projet sur SonarCloud
#sonar.projectKey=tpsonar

# Nom de ton organisation sur SonarCloud
#sonar.organization=quesque

# Où se trouve le code source à analyser
#sonar.sources=src

# Quel langage analyser
#sonar.language=php



#sonar.branch.name=main

sonar.projectKey=tpsonar
sonar.organization=quesque

# Où se trouve le rapport de couverture généré par PHPUnit
sonar.php.coverage.reportPaths=coverage/clover.xml

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=tpsonar
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8