# Identifiant unique de ton projet sur SonarCloud
sonar.projectKey=tpsonar

# Nom de ton organisation sur SonarCloud
sonar.organization=quesque

# Où se trouve le code source à analyser
sonar.sources=src

# Quel langage analyser
sonar.language=php

# Où se trouve le rapport de couverture généré par PHPUnit
sonar.php.coverage.reportPaths=coverage/clover.xml